# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 760a0a1b9d0e3e4abb5ec89048c12e2d5ea61829be118306f8d8a25c2acfb226fb650347dfd331916e3abcb30ecb055013c4360f553779b481af54e001d97c50

test:
  secret_key_base: 1a5052892d8d19e23877fff0a54bc8cca6b18ac24d5a45e658e524ba1e35348aff080827ee9a3e27d33618431b2d1993a78dfbfce7cfd78647b216f322ed89bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
